name: CI

on:
  #manually trigger runs
  workflow_dispatch:

jobs:
   build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         ls
         clang++ cct.cc -o a.out -Wall
         sudo apt-get install valgrind
         valgrind ./a.out
